## TFID and ML Alogrithms
1. Preprocessing and Cleaning
2. Train Test Split
3. BOW or TFID (Sentences---->Vectors) {Preventing the data leakage}
4. Trained the mode;

In [1]:
import pandas as pd
import numpy as np
messages=pd.read_csv('SMSSpamCollection', sep='\t', names=['label','messages'])

In [2]:
messages

label                                           messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
## DATA CLEANING AND PREPROCESSING
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range (0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['messages'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [7]:
## Output Features
y=pd.get_dummies(messages['label'])
y=y.astype(int)
y=y.iloc[:,0]

In [8]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [9]:
## Create the TFID model
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [10]:
len(X_train),len(y_train)

(4457, 4457)

In [12]:
# Independent Features
X_train=tfid.fit_transform(X_train).toarray()
X_test=tfid.transform(X_test).toarray()

In [13]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
np.set_printoptions(edgeitems=30, linewidth=100000,
                   formatter=dict(float=lambda x: "%.3g" % x))

In [16]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.221, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [17]:
tfid.vocabulary_

{'go': 813,
 'stay': 1977,
 'dont': 555,
 'know': 1086,
 'second': 1807,
 'time': 2124,
 'weak': 2349,
 'like': 1155,
 'keep': 1068,
 'eat': 593,
 'day': 491,
 'anyth': 73,
 'chang': 325,
 'sure': 2037,
 'noth': 1445,
 'wat': 2334,
 'make': 1243,
 'thk': 2110,
 'fall': 658,
 'actual': 16,
 'quit': 1665,
 'lucki': 1224,
 'dad': 479,
 'home': 956,
 'ask': 104,
 'come': 392,
 'fetch': 679,
 'alreadi': 50,
 'ask come': 107,
 'feel': 672,
 'better': 169,
 'bad': 140,
 'even': 631,
 'want': 2323,
 'one': 1486,
 'make feel': 1245,
 'feel better': 673,
 'sam': 1783,
 'meet': 1277,
 'hous': 973,
 'wow': 2435,
 'old': 1483,
 'airport': 39,
 'rd': 1685,
 'lor': 1193,
 'cant': 291,
 'els': 601,
 'bath': 149,
 'dog': 551,
 'later': 1110,
 'drive': 573,
 'train': 2172,
 'privat': 1636,
 'account': 9,
 'statement': 1974,
 'fone': 712,
 'show': 1861,
 'un': 2223,
 'redeem': 1705,
 'point': 1603,
 'call': 240,
 'identifi': 996,
 'code': 370,
 'expir': 652,
 'privat account': 1637,
 'account statement':

In [18]:
from sklearn.naive_bayes import MultinomialNB

In [19]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [20]:
y_pred=spam_detect_model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score,classification_report

In [22]:
accuracy_score(y_test,y_pred)

0.97847533632287

In [23]:
cs=classification_report(y_test,y_pred)

In [24]:
print(cs)

              precision    recall  f1-score   support

           0       0.99      0.84      0.91       147
           1       0.98      1.00      0.99       968

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

